name: 'Issue Linker'
description: 'Links the issue with the pull request on ZenHub'
author: 'Rojan Gh.'

# Define your inputs here.
inputs:
  token:
    required: true
    description: Token
  zenhub-key:
    default: ''
    required: false
    description: ZenHub's API Key
  zenhub-workspace:
    default: ''
    required: false
    description: ZenHub's Workspace Id

runs:
  using: node20
  main: dist/index.js
